### PR TITLE
Added - emg.ipynb and CSV File for emg & ecg

### PR DESCRIPTION
**Pull request by PayalLakra**
@lorforlinux 
I have done the following things:
- added csv sample file of ecg and emg
- done emg.ipynb(plot raw signal, plot filtered signal with envelope)
- rename ECG.ipynb file to ecg.ipynb
- eog.py file has some issues:
     ->When there is no eye blink and the window has a straight signal for that entire screen, some noise is also considered as peaks, which is wrong.
     -> Moving Window approach detects some wrong peaks, which means the approach is not applied properly here
- Change the timestamp for the csv file(now the csv file records only in microseconds) and adding extra relevant information like Arduino board, sampling rate in csv file recording at top.

### CODE REVIEW

**Comment by PayalLakra** [comment]
@lorforlinux 
I have resolved the issue in eog.py:
- when no eye blink and straight line appears then also some noise are considered as peaks, which is resolved now.
- Moving Window approach applied correctly now.

**Comment by PayalLakra** [comment]
I have done following things:
- Update eog.py file(Now it skips first 2 sec data to prevent detecting false peaks)
- Update with the eog.ipynb
- Create a new recordings folder for all csv files samples
- Update the new csv filename

**Comment by PayalLakra** [comment]
@lorforlinux 
I have made following changes:
- Update the saved csv file format as discussed.
- Update readme according to new changes
- Add a new file keystroke.py in applications folder(Works as press spacebar whenever an eye blink detected- with 3 buttons Blink detected, start and quit)

**Comment by PayalLakra** [comment]
@lorforlinux 
I have updated the code for chords.py file in which now it supports more boards -UNO Clone and Rasberry pi pico

**Comment by lorforlinux** [comment]
@PayalLakra Thank you so much for your contribution, I am merging this now.

**Pull request merged**
